수정: 스터디룸 관련 코드 리팩토링 및 에러 헨들링 추가
YAPP-18th/ML-Team-Backend pull request #20
Opened 2021-05-11 06:31 UTC by 0417taehyun

- 스터디룸 관련 엔드포인트 코드 리팩토링
- `schemas` 디렉토리 내에 공통 성공, 실패 응답 `BaseModel` 을 `responses.py` 파일에 정의
- 에러 헨들링을 위한 `errors` 디렉토리 생성
- 테스트 코드 내에 불필요한 `product` 관련 기능 삭제

2021-05-11 14:12 UTC, Limm-jk requested changes
그렇습니다

2021-05-11 14:12 UTC, Limm-jk commented on app/api/study_rooms.py
> +    elif response == 'NOT_FOUN_ROOM':
NOT_FOUND_ROOM 인 것 같습니다!

2021-05-12 12:01 UTC, Limm-jk requested changes
개인적인 생각을 담아보았습니다. 괜찮으셨다면 수용하셔도 좋을 것 같고, 아니라면 ? 머임? 하고 넘어가셔도 좋을 것 같습니다 :)

어제 이야기했는데, 굉장하시네요..! 저도 빨리 작업해두겠습니다.

2021-05-12 12:01 UTC, Limm-jk commented on app/api/study_rooms.py
> +        return JSONResponse(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, content={'detail': 'server error'})
Generic Exception을 잡아줄 때, traceback을 사용해보는 것은 어떨까요?
보다 디테일한 정보를 전달할 수 있으리라 생각이 됩니다 :)
아래에 어떤 식으로 사용될 지 간단하게 써보았습니다. 좀 조잡하네요 ㅎㅎ,,,,

![image](https://user-images.githubusercontent.com/57378834/117972481-2bee3680-b366-11eb-8f78-52146bed16f8.png)

2021-05-12 12:01 UTC, Limm-jk commented on app/crud/study_rooms.py
> +            print(error)
앗 여기서 로깅을 해주고 있었군요! ㅎㅎ

2021-05-12 12:01 UTC, Limm-jk commented on app/crud/study_rooms.py
> +                return ''
여기서의 ''은 무엇을 의미하는 것일까요?

2021-05-12 12:01 UTC, Limm-jk commented on app/crud/study_rooms.py
> +            print(error)
여기서도 traceback을 사용해주는 것은 어떨까요?
1. logging.error(traceback.format_exec)
2. traceback.print_exec()

2021-05-12 12:01 UTC, Limm-jk commented on app/crud/study_rooms.py
> +            print(error)
log를 찍어줄 때, 정보를 조금 더 담아도 좋을 것 같아요!
f'Study Room(ID : {room_id}) Not Found' 같은 예시를 들 수 있을 것 같습니다 :)

2021-05-12 12:01 UTC, Limm-jk commented on app/crud/study_rooms.py
> +                raise InvalidArgumentException(message='filed required')
메세지가 이야기하고자 하는 바가 불명확한 것 같습니다.
어떤 파일을 지칭하는 것일까요?

2021-05-12 12:01 UTC, Limm-jk commented on requirements.txt
> +<<<<<<< HEAD
conflict가 해결되지 않은 부분이 있습니다.

2021-05-12 12:33 UTC, 0417taehyun commented on requirements.txt
> +<<<<<<< HEAD
해결했습니다.

2021-05-12 12:34 UTC, 0417taehyun commented on app/crud/study_rooms.py
> +                return ''
`create` , `update` ,  `remove` 의 경우 넘겨줄 데이터가 없기 때문에 `''` 으로 표현했는데 해당 부분 아예 `return` 없는 것으로 변경했습니다.

2021-05-12 12:36 UTC, 0417taehyun commented on app/crud/study_rooms.py
> +            print(error)
`traceback` 을 처음 알았네요. 알려주신 방법 사용해서 오류 추적했습니다.

기존 CRUD 내에 작성하던 전체 `Exception` 을 제거하고 API에서 로그 처리하는 걸로 변경했습니다. 조건문 `else`에서 `raise` 할 경우 해당 오류를 그대로 CRUD 내의 `Exception` 에서 잡혀서 `'server error'` 로 출력하는 문제 때문에 바꿨습니다.

로그의 경우 이전에 제안드렸던 방법 처럼 파일로 저장하는 것이 좋지 않을까 싶어서 우선 대략적인 추적 용으로만 작성했습니다. 우선 배포가 아닌 개발 단계에서는 알려주신 `traceback` 으로 충분히 알 수 있을 것 같습니다.

2021-05-12 12:39 UTC, 0417taehyun commented on app/crud/study_rooms.py
> +                raise InvalidArgumentException(message='filed required')
해당 오류에서는 문장 그대로 `query` , `body` 등의 `field` 에 담겨 있어야 할 데이터가 담기지 않아 해당 `field required` 하다는 의미입니다. 커스텀 오류에 `message` 파라미터를 입력하게 했는데 이는 저희가 응답으로 `detail` 에 담아 넘기는 `msg` 부분을 의미하는 파라미터로 설정했습니다. 그래서 로직 내에서도 `get_detail()` 함수의 파라미터 중 `message` 부분에 해당 오류의 메세지가 값으로 들어갑니다.

2021-05-12 13:37 UTC, Limm-jk commented on app/crud/study_rooms.py
> +            print(error)
LGTM

2021-05-12 13:49 UTC, Limm-jk requested changes
고생 많으십니다,,,!

2021-05-12 13:49 UTC, Limm-jk commented on app/crud/study_rooms.py
> +                raise InvalidArgumentException(message='filed required')
말씀해주신 사항에 의하면 해당 라인은 오타인 것으로 생각이 듭니다!!

filed required -> field required

2021-05-12 13:49 UTC, Limm-jk commented on app/crud/study_rooms.py
> +                raise InvalidArgumentException(message='filed required')
여기에도 동일합니다.

2021-05-12 13:49 UTC, Limm-jk commented on app/api/study_rooms.py
> +        return JSONResponse(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, content={'detail': 'server error'})
혹시 여기, 그리고 api서비스의 Generic Exception의 detail에서 traceback을 넣어주는 것은 어떠할 지 제안드려봅니다!

이전의 회의에서 front에서 어떠한 오류가 일어나고 있는 지 아는 것이 좋을 것 같다 이야기하신 것으로 알고 있는데,
status로 알 수 있는 internal server error 대신 `traceback.format_exec()`을 넣어주는 것도 괜찮을 것 같습니다.

의견 남겨주세요 :)

2021-05-12 14:12 UTC, Limm-jk commented on app/crud/study_rooms.py
> +            raise NoSuchElementException(message='not fund')
앗 발견하지 못한 오타가..!

2021-05-12 14:13 UTC, Limm-jk approved these changes
오타만 수정하시고 merge하시면 될 것 같습니다 :)

2021-05-12 14:14 UTC, Limm-jk commented
LGTM 👍

2021-05-12 14:14 UTC, merged