[ 추가 ] 스터디룸 입장 엔드포인트 및 소켓 통신
YAPP-18th/ML-Team-Backend pull request #30
Opened 2021-05-19 07:05 UTC by 0417taehyun

- 스터디룸 입장 엔드포인트  `POST /{room_id}/join` 추가
- 소켓 통신 추가 ( `connect` , `response` , `status` , `joinRoom` , `leaveRoom` 이벤트)
- CORS (현재 진행 중 Class로 만들 예정)

2021-05-19 11:58 UTC, Limm-jk requested changes
고생 많으셨습니다!! 이번 pr도 굉장히 많이 작업을 해주셔서 항상 감사드립니다.

개인적인 의견을 간단하게 첨부해보았습니다.

역시 socket의 세계는 어렵네요 ㅠㅠ

2021-05-19 11:58 UTC, Limm-jk commented on app/api/study_rooms.py
> +        print(db)
혹시 여기서의 로깅은 어떠한 추적을 위해서 사용하신 것일지 여쭈어봐도 될까요?

2021-05-19 11:58 UTC, Limm-jk commented on app/api/study_rooms.py
> +        db.close()
👍

2021-05-19 11:58 UTC, Limm-jk commented on app/crud/study_rooms.py
> +            data = db.query(self.model).filter(self.model.id == UUID(room_id)).first()
해당 로직만 crud에 추가한 후, service에서 가져다 쓰는 것도 좋을 것 같다고 제안을 드려봅니다!

이 로직에서 db에 접근하는 것은 일부고, 서비스에 보다 가깝다고 생각이 들어서요!

2021-05-19 11:58 UTC, Limm-jk commented on app/crud/study_rooms.py
> +                if study_room['current_join_counts'] >= 5:
MagicNumber는 지양하시는 것이 좋을 것 같습니다!

status코드 같이 예외를 적용할만한 상수가 아니라면 상수는 상단에서 먼저 const로 정의해주고 변수를 가져다 쓰는 것이 좋을 것 같습니다.

MAX_CAPACITY = 5 와 같은 식으로 사용할 수 있을 것 같습니다.

2021-05-19 11:58 UTC, Limm-jk commented on app/errors/customs.py
> +    def __init__(self, message: str):
타입힌트 넣은 것 좋은 것 같습니다

2021-05-19 11:58 UTC, Limm-jk commented on app/database/base_class.py
> +        return {c.key: getattr(self, c.key) for c in inspect(self).mapper.column_attrs}
해당 로직은 어떠한 역할을 하는 지 잘 이해를 못했습니다.

한번 여쭈어봐도 될까요?

2021-05-19 11:58 UTC, Limm-jk commented on app/service/sockets.py
> +    study_room = db.query(model).filter(model.id == UUID(room_id)).update(
이 부분도 crud에 만들고 가져오는 방식이 더욱 좋을 것 같습니다.

2021-05-19 11:58 UTC, Limm-jk commented on app/service/sockets.py
> +        db.commit()
orm의 transaction은 crud 내에서 처리되었으면 하는 바람이 있습니다.

이는 orm이 가지고 있는 특유의 영속성 때문입니다.

uncommit된 객체는 service에서 사용될 때 어떠한 변화를 일으킬 지 모르는 무서운 존재라고 생각합니다.
영속성을 의도하지 않으셨다면 이 부분이 crud로 들어가고 가져와서 쓰는 것이 어떤가 생각합니다.

2021-05-19 11:58 UTC, Limm-jk commented on app/main.py
> +    uvicorn.run('app.main:server', host="0.0.0.0", port=8000, reload=True, debug=True)
debug를 추가하는 것이 어떠한 로직적인 변화를 주는 것인지 여쭈어봐도 될까요?

혹시 실행 레벨을 디버그로 가져가는 것이라면 커밋에는 반영하지 않는 것이 좋을 것 같습니다.

2021-05-19 12:35 UTC, 0417taehyun commented on app/api/study_rooms.py
> +        print(db)
안 그래도 말씀드리려고 했는데 제가 까먹고 공유를 못 드렸네요.

현재 발생하는 오류 중에 `/study-rooms/{room_id}/join` 부분으로 엔드포인트 요청을 한다고 했을 때 `/{room_id}/` 부분을 아예 없이, 이를 테면 `/study_rooms//join` 과 같은 형태로 요청했을 때 `stack overflow` 오류가 발생하더라고요. 근데 관련해서 `except Exception` 으로 잡히지 않아서 우선 알아보는 중입니다.

`print(db)` 를 통해서 `room_id` 가 없는 경우로 넘어와 해당 값이 `None` 으로 넘어올 것이라 예상해서 찍었었던 로그이지만 그렇게 진행이 안 되고 아예 데이터베이스 쿼리에서 오류가 나는 것 같아 해당 부분 찾아 본 결과 `jsonable_encoder` 부분에서 발생하는 오류일 수도 있다고 아래 어떤 용도로 사용하는지 물으셨던 `database` 디렉토리에서 사용한 `as_dict` 부분을 `jsonable_encoder` 대신 사용하는 걸 해결책으로 GitHub Issue에서 본 적이 있어 테스트 해보려고 작성했습니다.

테스트 해 본 결과 우선 해결은 안 되고 있고 다른 기능 구현이 우선인 것 같아 일단 보고서까지 작업 이후 다시 진행할 예정입니다.

2021-05-19 12:35 UTC, 0417taehyun commented on app/service/sockets.py
> +        db.commit()
해당 부분 `crud` 에서 만들어 가져오는 걸로 수정해보겠습니다.

2021-05-19 12:35 UTC, 0417taehyun commented on app/main.py
> +    uvicorn.run('app.main:server', host="0.0.0.0", port=8000, reload=True, debug=True)
유무에 따른 차이점을 보고 싶어서 적었던 매개변수인데 미반영하도록 하겠습니다.

2021-05-19 12:35 UTC, 0417taehyun commented on app/database/base_class.py
> +        return {c.key: getattr(self, c.key) for c in inspect(self).mapper.column_attrs}
위 `print(db)` 로그 확인의 이유에 대한 질문에 관련된 답변 자세하게 적었습니다.

간단하게 다시 설명드리면 오류 해결 방안으로 GitHub Issue에서 `jsonable_encoder` 대신 해당 함수를 만들어 사용하는 걸 봤어서 시도해봤습니다. 우선 Dev Camp 때까지 관련 오류 보다 다른 기능 구현이 우선인 것 같아서 후조치로 미뤄둔 상태입니다.

2021-05-19 12:35 UTC, 0417taehyun commented on app/errors/customs.py
> +    def __init__(self, message: str):
감사합니다 🙇

2021-05-19 12:35 UTC, 0417taehyun commented on app/service/sockets.py
> +    study_room = db.query(model).filter(model.id == UUID(room_id)).update(
네 알겠습니다

2021-05-19 12:35 UTC, 0417taehyun commented on app/crud/study_rooms.py
> +                if study_room['current_join_counts'] >= 5:
해당 부분 `config` 에서 상수로 정의 후 가져다 쓰는 방법으로 변경하겠습니다.

2021-05-19 12:35 UTC, 0417taehyun commented on app/crud/study_rooms.py
> +            data = db.query(self.model).filter(self.model.id == UUID(room_id)).first()
관련 부분 `service` 로 변경하겠습니다.

2021-05-19 12:42 UTC, Limm-jk commented on app/database/base_class.py
> +        return {c.key: getattr(self, c.key) for c in inspect(self).mapper.column_attrs}
개발 중인 기능은 
```
# TODO: 기능 
```

과 같이 남겨주시면 감사하겠습니다 :)

2021-05-19 13:10 UTC, 0417taehyun commented on app/database/base_class.py
> +        return {c.key: getattr(self, c.key) for c in inspect(self).mapper.column_attrs}
네 알겠습니다.

2021-05-19 14:28 UTC, 0417taehyun commented
문제점: `db` 를 `api` 에서 처럼 `Depends` 로 사용하고 싶었으나 `api` 에서의 데이터베이스 접근은 FastAPI의 내부 로직, `router` 를 거치고 난 뒤의 데이터베이스 접근인지 `Depends(get_db)` 를 따로 소켓에서 사용하려는 시도가 작동하지 않습니다. `get_db` 함수를 따로 빼서 사용하려는 시도도 `generator` 에는 쿼리가 동작하지 않는다고 나와 우선은 `Sessionlocal` 을 `import` 했습니다. 관련된 쿼리 로직 자체는 `crud` 에서 해결했습니다.

2021-05-20 11:13 UTC, Limm-jk approved these changes
고생 많으셨습니다 :)

혹시 가능하시다면 이후 버전 추적을 위하여 작업한 사항에 대하여 커밋을 유지하고 올려주시면 정말 감사드리겠습니다 :)

2021-05-20 11:47 UTC, merged